name: 'Create Pull Request for Another Repository'
description: 'Used for pull request a copy of a folder to another repository'
inputs:
  destination_repo:
    description: 'Destination repository'
    required: true
  user_email:
    description: 'Email for the git commit'
    required: true
  user_name:
    description: 'GitHub username for the commit'
    required: true
  destination_head_branch:
    description: 'The branch to create to push the changes. Cannot be master or main'
    required: true
  destination_base_branch:
    description: 'The branch into which you want your code merged.'
    required: false
    default: "main"
  title:
    description: 'The title of the pull request'
    required: false
    default: "Update from ${{ github.ref }}"
  body:
    description: 'The body of the pull request'
    required: false
    default: "This is an automated pull request by [haiiliin/action-pull-request-another-repo](https://github.com/haiiliin/action-pull-request-another-repo)."
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.source-folder }}
    - ${{ inputs.destination-repo }}
    - ${{ inputs.destination-folder }}
    - ${{ inputs.user-email }}
    - ${{ inputs.user-name }}
    - ${{ inputs.destination-head-branch }}
    - ${{ inputs.destination-base-branch }}
    - ${{ inputs.title }}
    - ${{ inputs.body }}
branding:
  icon: 'git-commit'
  color: 'green'
